# Generated by Django 5.1 on 2024-08-17 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_column='email', max_length=256, null=True)),
            ],
            options={
                'db_table': 'player',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game_app.player')),
            ],
            options={
                'db_table': 'leader_board',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(default='         ', max_length=9)),
                ('is_player_turn', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('win', 'Win'), ('lose', 'Lose'), ('draw', 'Draw')], max_length=10)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_app.player')),
            ],
            options={
                'db_table': 'game',
                'managed': True,
            },
        ),
    ]
